### ISSUE TITLE
多次调用wx-caman 的greyscale后, 转化速度明显下降

### ISSUE THREAD

**Issue by yuanzhanghu** [ChrisCindy/wx-caman#10]
刚开始greyscale大概0.3-0.5秒. 
大约50次greyscale之后, 每次的greyscale转换速度需要2-3秒的样子,

**Comment by ChrisCindy** [comment]
@yuanzhanghu 应该是微信小程序 canvas 组件支持问题。

**Comment by yuanzhanghu** [comment]
没错! 错怪wx-caman了, 发现实际上canvas绘图需要每次清空, 否则直接在上次的canvas上继续画,  才会越来越慢.

**Comment by yuanzhanghu** [comment]
不是wx-caman的问题.
