### ISSUE TITLE
可以在canvas区域加载一张图片吗？并且给图片使用滤镜效果。

### ISSUE THREAD

**Issue by lfc520** [ChrisCindy/wx-caman#3]
我直接在new WxCaman加图片地址，好像不行。

 wx.getImageInfo({
          src: self.data.imgUrl,
          success: function (res) {
            var ctx = wx.createCanvasContext('canvasImg');
            self.setData({
              canvasWidth: res.width,
              canvasHeight: res.height
            })
            // ctx.drawImage(self.data.imgUrl, 0, 0, res.width, res.height)
            ctx.draw(false, res.width, res.height, function () {
              new WxCaman('canvasImg','self.data.imgUrl', function () {
                this.brightness(90)
                this.contrast(90)
                this.sepia(90)
                this.saturation(-90)
                this.render()
              })
            })
          }
        })

**Comment by ChrisCindy** [comment]
@lfc520 是否调用 `new WxCaman(...)` 时传参有问题？
按照以下示例可加载图片并对其进行滤镜渲染
```js
const ctx = wx.createCanvasContext('canvas')
ctx.drawImage(imgFilePath, x, y, width, height)
ctx.draw(false, function() {
      // 300 200 为 canvas 组件真实宽高
      new WxCaman('canvas', 300, 200, function () {
        this.brightness(10)
        this.contrast(30)
        this.sepia(60)
        this.saturation(-30)
        this.render()
      })
    })
```

**Comment by lfc520** [comment]
可以了，谢谢。
但是还有一个疑问：图片的渲染时间比较长，我想让图片在渲染过程中有个toast提醒，渲染结束后，toast关闭。不知道渲染完成的标志是什么？我把wx.hideLoading()加在了this.render()后面，但是好像没渲染完，toast就关闭了。不知道什么问题，谢谢。
