### ISSUE TITLE
不支持event事件的话，怎么实现滤镜添加完毕的之后事件处理？

### ISSUE THREAD

**Issue by Mohaiyo** [ChrisCindy/wx-caman#7]
请问下滤镜添加完毕之后的回调可以实现吗？
如下图，我想添加一个渲染中的loading效果。。。但是貌似render完毕之前就关闭了
![image](https://user-images.githubusercontent.com/22421509/48929815-03201f80-ef27-11e8-81d4-63af917ee76e.png)

**Comment by fandongjiqi** [comment]
render()里面可以直接写回调的function

**Comment by fandongjiqi** [comment]
> 请问下滤镜添加完毕之后的回调可以实现吗？
> 如下图，我想添加一个渲染中的loading效果。。。但是貌似render完毕之前就关闭了
> ![image](https://user-images.githubusercontent.com/22421509/48929815-03201f80-ef27-11e8-81d4-63af917ee76e.png)

render里面直接给一个function就可以了，执行完毕后触发

**Comment by Mohaiyo** [comment]
> > 请问下滤镜添加完毕之后的回调可以实现吗？
> > 如下图，我想添加一个渲染中的loading效果。。。但是貌似render完毕之前就关闭了
> > ![image](https://user-images.githubusercontent.com/22421509/48929815-03201f80-ef27-11e8-81d4-63af917ee76e.png)
> 
> render里面直接给一个function就可以了，执行完毕后触发

可以了，谢谢
