### ISSUE TITLE
会被覆盖处理

### ISSUE THREAD

**Issue by Surile** [ChrisCindy/wx-caman#9]
有多个滤镜，每次点击的时候，不是清空上一个，而是合并了上一个和当前点击的

**Comment by Surile** [comment]
@ChrisCindy  ?

**Comment by ChrisCindy** [comment]
@Surile 可否上代码说明？描述不是很清楚。

**Comment by Surile** [comment]
![image](https://user-images.githubusercontent.com/28652894/50279012-87f94d00-0483-11e9-8d29-3cf6916d8e68.png)
我定义了这几个滤镜，然后循环渲染。
点击时调用的方法：
![image](https://user-images.githubusercontent.com/28652894/50279051-a52e1b80-0483-11e9-815e-38a9f55290f4.png)

当点击第二个或者以上滤镜的时候。会在之前的滤镜上进行渲染

**Comment by Surile** [comment]
@ChrisCindy

**Comment by ChrisCindy** [comment]
@Surile 建议每次点击切换滤镜的时候使用小程序的 API 重新初始化 canvas 组件的内容（比如如果 canvas 组件内读入的是图片，可以使用 `drawImage`）

**Comment by Surile** [comment]
好的。了解
